/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Família Oliveira
 */
public class frmQuiz extends javax.swing.JFrame {

    /**
     * Creates new form frmQuiz
     */
    public frmQuiz() {
        initComponents();
    }
    String pergunta, resposta, alternativa = "";
    int chances = 3;
    int i = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perg = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ch = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        alt1 = new javax.swing.JRadioButton();
        alt2 = new javax.swing.JRadioButton();
        alt3 = new javax.swing.JRadioButton();
        alt4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(116, 173, 176));

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton3.setText("Voltar para o menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton4.setText("Enviar resposta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, jButton4});

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 490, 600, 60);

        jPanel2.setBackground(new java.awt.Color(116, 173, 176));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(116, 173, 176), new java.awt.Color(116, 173, 176)));

        perg.setEditable(false);
        perg.setColumns(20);
        perg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        perg.setLineWrap(true);
        perg.setRows(5);
        perg.setWrapStyleWord(true);
        perg.setAutoscrolls(false);
        perg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(perg);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 580, 140);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 173, 176), 3));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Chances: ");

        ch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ch.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ch, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(ch))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 240, 137, 41);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        alt1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt1);
        alt1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        alt1.setText("*");
        alt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt1ActionPerformed(evt);
            }
        });

        alt2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt2);
        alt2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        alt2.setText("*");
        alt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt2ActionPerformed(evt);
            }
        });

        alt3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt3);
        alt3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        alt3.setText("*");
        alt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt3ActionPerformed(evt);
            }
        });

        alt4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt4);
        alt4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        alt4.setText("*");
        alt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(alt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 290, 580, 200);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jPanel1.add(img);
        img.setBounds(0, 0, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Limpa() {
        alt1.setSelected(false);
        alt2.setSelected(false);
        alt3.setSelected(false);
        alt4.setSelected(false);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frmMenu x = new frmMenu();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (alt1.isSelected() || alt2.isSelected() || alt3.isSelected() || alt4.isSelected()) {
            try {
                Conexao.Conectar();
                Conexao.ps = Conexao.con.prepareStatement("SELECT * FROM resposta WHERE res_niv_id = " + frmMenu.dificuldade + " AND res_num = " + i);
                Conexao.rs = Conexao.ps.executeQuery();
                if (Conexao.rs.next()) {
                    if (alternativa.equals(Conexao.rs.getString("res_rescorreta"))) {
                        if (frmMenu.dificuldade == 1) {
                            try {
                                Conexao.Conectar();
                                Conexao.ps = Conexao.con.prepareStatement("UPDATE jogador SET jog_acfacil = jog_acfacil + 1, jog_acertos = jog_acertos + 1  WHERE jog_nickname = '" + frmLogin.nick + "'");
                                Conexao.ps.executeUpdate();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, ex);
                            }

                        } else if (frmMenu.dificuldade == 2) {
                            try {
                                Conexao.Conectar();
                                Conexao.ps = Conexao.con.prepareStatement("UPDATE jogador SET jog_acmedio = jog_acmedio + 1, jog_acertos = jog_acertos + 1  WHERE jog_nickname = '" + frmLogin.nick + "'");
                                Conexao.ps.executeUpdate();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, ex);
                            }
                        } else if (frmMenu.dificuldade == 3) {
                            try {
                                Conexao.Conectar();
                                Conexao.ps = Conexao.con.prepareStatement("UPDATE jogador SET jog_acdificil = jog_acdificil + 1, jog_acertos = jog_acertos + 1  WHERE jog_nickname = '" + frmLogin.nick + "'");
                                Conexao.ps.executeUpdate();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, ex);
                            }
                        }

                        JOptionPane.showMessageDialog(null, "Parabens, você acertou!");
                        i++;
                        dados();
                    } else {
                        if (chances <= 1) {
                            this.setVisible(false);
                            if (JOptionPane.showConfirmDialog(null, "Suas chances acabaram :(\nA alternativa correta era:\n" + Conexao.rs.getString("res_rescorreta") + "\nDeseja tentar novamente!", "Suas chances acabaram! ;-;", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                i = 1;
                                chances = 3;
                                ch.setText("" + chances);
                                dados();
                                this.setVisible(true);
                            } else {
                                if (JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu?", "Voltar para o menu", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                    frmMenu x = new frmMenu();
                                    x.setVisible(true);
                                } else {
                                    i = 1;
                                    chances = 3;
                                    ch.setText("" + chances);
                                    dados();
                                    this.setVisible(true);
                                }
                            }
                        } else {
                            chances--;
                            ch.setText("" + chances);
                            JOptionPane.showMessageDialog(null, "Alternativa errada, você tem mais " + chances + " chances de acertar");
                            try {
                                Conexao.Conectar();
                                Conexao.ps = Conexao.con.prepareStatement("UPDATE jogador SET jog_erros = jog_erros + 1 WHERE jog_nickname = '" + frmLogin.nick + "'");
                                Conexao.ps.executeUpdate();

                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, ex);
                            }
                        }
                    }

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma resposta!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dados();
        ch.setText("" + chances);
    }//GEN-LAST:event_formWindowOpened

    private void alt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt1ActionPerformed
        alternativa = alt1.getText();
    }//GEN-LAST:event_alt1ActionPerformed

    private void alt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt2ActionPerformed
        alternativa = alt2.getText();
    }//GEN-LAST:event_alt2ActionPerformed

    private void alt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt3ActionPerformed
        alternativa = alt3.getText();
    }//GEN-LAST:event_alt3ActionPerformed

    private void alt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt4ActionPerformed
        alternativa = alt4.getText();
    }//GEN-LAST:event_alt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alt1;
    private javax.swing.JRadioButton alt2;
    private javax.swing.JRadioButton alt3;
    private javax.swing.JRadioButton alt4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel ch;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea perg;
    // End of variables declaration//GEN-END:variables

    public void dados() {
        try {
            Conexao.Conectar();
            Conexao.ps = Conexao.con.prepareStatement("SELECT * FROM pergunta WHERE per_niv_id = " + frmMenu.dificuldade);
            Conexao.rs = Conexao.ps.executeQuery();
            if (Conexao.rs.next()) {
                if (i < 5) {
                    pergunta = Conexao.rs.getString("per_perg" + i);
                    perg.setText(pergunta);
                    Conexao.ps = Conexao.con.prepareStatement("SELECT * FROM resposta WHERE res_niv_id = " + frmMenu.dificuldade + " AND res_num = " + i);
                    Conexao.rs = Conexao.ps.executeQuery();
                    if (Conexao.rs.next()) {
                        alt1.setText(Conexao.rs.getString("res_resp1"));
                        alt2.setText(Conexao.rs.getString("res_resp2"));
                        alt3.setText(Conexao.rs.getString("res_resp3"));
                        alt4.setText(Conexao.rs.getString("res_resp4"));
                    }
                } else {
                    this.setVisible(false);
                    if (JOptionPane.showConfirmDialog(null, "Parabéns!\nVocê concluiu o quiz!\nDeseja jogar novamente?", "Acabou!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        i = 1;
                        chances = 3;
                        ch.setText("" + chances);
                        dados();
                        this.setVisible(true);
                    } else {
                        if (JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu?", "Voltar para o menu", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                            frmMenu x = new frmMenu();
                            x.setVisible(true);
                        } else {
                            i = 1;
                            chances = 3;
                            ch.setText("" + chances);
                            dados();
                            this.setVisible(true);
                        }
                    }
                    ch.setText("" + chances);
                    i = 1;
                    chances = 3;
                    dados();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

}
